# Generated by Django 5.2 on 2025-05-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_marketing',
            field=models.BooleanField(default=False, verbose_name='Receive Marketing Communications'),
        ),
    ]
