# Generated by Django 5.2 on 2025-04-19 07:43

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'indexes': [models.Index(fields=['name'], name='ecommerce_c_name_f3a40e_idx'), models.Index(fields=['created_at'], name='ecommerce_c_created_17ce26_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('is_new', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('units_per_pack', models.PositiveIntegerField(default=1, help_text='Number of units per pack')),
                ('units_per_pallet', models.PositiveIntegerField(default=1, help_text='Number of units per pallet')),
                ('show_units_per', models.CharField(choices=[('none', 'None'), ('pack', 'Pack Only'), ('pallet', 'Pallet Only'), ('both', 'Both Pack and Pallet')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='ecommerce.product')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_type', models.CharField(choices=[('pack', 'Pack'), ('pallet', 'Pallet')], max_length=10)),
                ('range_start', models.PositiveIntegerField()),
                ('range_end', models.PositiveIntegerField(blank=True, help_text="Leave blank for 'X+' ranges", null=True)),
                ('price_per_pack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='ecommerce.productvariant')),
            ],
            options={
                'verbose_name': 'pricing tier',
                'verbose_name_plural': 'pricing tiers',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('is_physical_product', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_unit', models.CharField(blank=True, choices=[('lb', 'Pounds (lb)'), ('kg', 'Kilograms (kg)'), ('oz', 'Ounces (oz)'), ('g', 'Grams (g)')], max_length=2, null=True)),
                ('track_inventory', models.BooleanField(default=False)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.productvariant')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='TableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('image', 'Image'), ('price', 'Price')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_fields', to='ecommerce.productvariant')),
            ],
            options={
                'verbose_name': 'table field',
                'verbose_name_plural': 'table fields',
            },
        ),
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value_image', models.ImageField(blank=True, null=True, upload_to='item_data_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='ecommerce.item')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_values', to='ecommerce.tablefield')),
            ],
            options={
                'verbose_name': 'item data',
                'verbose_name_plural': 'item data',
            },
        ),
        migrations.CreateModel(
            name='UserExclusivePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user exclusive price',
                'verbose_name_plural': 'user exclusive prices',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.item')),
            ],
            options={
                'verbose_name': 'item image',
                'verbose_name_plural': 'item images',
                'indexes': [models.Index(fields=['item'], name='ecommerce_i_item_id_c1583a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'name'], name='ecommerce_p_categor_65b574_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='ecommerce_p_created_281ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='ecommerce_p_product_378eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'name'], name='ecommerce_p_product_e53093_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['created_at'], name='ecommerce_p_created_f8801d_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingtier',
            index=models.Index(fields=['product_variant', 'tier_type'], name='ecommerce_p_product_6b2c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingtier',
            index=models.Index(fields=['created_at'], name='ecommerce_p_created_d71c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['product_variant'], name='ecommerce_i_product_b8852f_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['sku'], name='ecommerce_i_sku_18061a_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='ecommerce_i_status_ecb28b_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at'], name='ecommerce_i_created_585e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='tablefield',
            index=models.Index(fields=['product_variant', 'name'], name='ecommerce_t_product_8c847c_idx'),
        ),
        migrations.AddIndex(
            model_name='tablefield',
            index=models.Index(fields=['field_type'], name='ecommerce_t_field_t_8e7a25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tablefield',
            unique_together={('product_variant', 'name')},
        ),
        migrations.AddIndex(
            model_name='itemdata',
            index=models.Index(fields=['item', 'field'], name='ecommerce_i_item_id_9a9101_idx'),
        ),
        migrations.AddIndex(
            model_name='itemdata',
            index=models.Index(fields=['created_at'], name='ecommerce_i_created_60edab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemdata',
            unique_together={('item', 'field')},
        ),
        migrations.AddIndex(
            model_name='userexclusiveprice',
            index=models.Index(fields=['user', 'item'], name='ecommerce_u_user_id_00014c_idx'),
        ),
        migrations.AddIndex(
            model_name='userexclusiveprice',
            index=models.Index(fields=['created_at'], name='ecommerce_u_created_a54292_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userexclusiveprice',
            unique_together={('user', 'item')},
        ),
    ]
