# Generated by Django 5.2 on 2025-05-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', editable=False, max_length=10),
        ),
    ]
