# Generated by Django 5.2 on 2025-04-17 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tieredpricing',
            name='product',
        ),
        migrations.AddField(
            model_name='productvariantdata',
            name='value_image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_images/'),
        ),
        migrations.AlterField(
            model_name='productvariantdata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_values', to='ecommerce.tablefield'),
        ),
        migrations.AlterField(
            model_name='tablefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('image', 'Image')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='ecommerce_c_name_f3a40e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_at'], name='ecommerce_c_created_17ce26_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryimage',
            index=models.Index(fields=['category'], name='ecommerce_c_categor_86f0bd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'name'], name='ecommerce_p_categor_65b574_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='ecommerce_p_created_281ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['subcategory'], name='ecommerce_p_subcate_f03f78_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['created_at'], name='ecommerce_p_created_f8801d_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariantdata',
            index=models.Index(fields=['created_at'], name='ecommerce_p_created_4caa6a_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['product', 'name'], name='ecommerce_s_product_561791_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['created_at'], name='ecommerce_s_created_25a94b_idx'),
        ),
        migrations.AddIndex(
            model_name='tablefield',
            index=models.Index(fields=['field_type'], name='ecommerce_t_field_t_8e7a25_idx'),
        ),
        migrations.AddIndex(
            model_name='userexclusiveprice',
            index=models.Index(fields=['created_at'], name='ecommerce_u_created_a54292_idx'),
        ),
        migrations.DeleteModel(
            name='TieredPricing',
        ),
    ]
