# Generated by Django 5.2 on 2025-05-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional notes for the order.'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'item', 'pricing_tier', 'pack_quantity', 'unit_type')},
        ),
    ]
