# Generated by Django 5.2 on 2025-05-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_productvariant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='units_per_pallet',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of units per pallet'),
        ),
    ]
