# Generated by Django 5.2 on 2025-05-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_productvariant_units_per_pallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='height_in_inches',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Height converted to inches (automatically calculated).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='length_in_inches',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Length converted to inches (automatically calculated).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width_in_inches',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Width converted to inches (automatically calculated).', max_digits=10, null=True),
        ),
    ]
