# Generated by Django 5.2 on 2025-04-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='show_units_per',
            field=models.CharField(choices=[('pack', 'Pack Only'), ('pallet', 'Pallet Only'), ('both', 'Both Pack and Pallet')], default='pack', max_length=10),
        ),
    ]
