# Generated by Django 5.2 on 2025-04-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_productvariant_show_units_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtier',
            name='tier_type',
            field=models.CharField(choices=[('pack', 'Pack'), ('pallet', 'Pallet'), ('both', 'Both')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pricingtierdata',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text="Price per pack if tier_type is 'pack', per pallet if 'pallet', per pack/pallet if 'both'", max_digits=10),
        ),
    ]
