# Generated by Django 5.2 on 2025-05-04 14:10

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_item_height_in_inches_item_length_in_inches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='CartItem',
            name='subtotal',
            field=models.DecimalField(
                max_digits=12, 
                decimal_places=2, 
                editable=False, 
                default=Decimal('0.00'), 
                help_text="Total price of items in the cart (sum of item subtotals)."
            ),
        ),
    ]