# Generated by Django 5.2 on 2025-05-06 00:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_add_subtotal_to_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total cost before user-exclusive discounts (per pack price * quantity, adjusted for unit type).', max_digits=12),
        ),
    ]
