# Generated by Django 5.2 on 2025-04-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_pricingtier_tier_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtier',
            name='tier_type',
            field=models.CharField(choices=[('pack', 'Pack'), ('pallet', 'Pallet')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pricingtierdata',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text="Price per pack if tier_type is 'pack', per pallet if 'pallet'", max_digits=10),
        ),
    ]
