# Generated by Django 5.2 on 2025-05-01 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_remove_order_updated_at_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user_exclusive_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartitem_items', to='ecommerce.userexclusiveprice'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user_exclusive_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitem_items', to='ecommerce.userexclusiveprice'),
        ),
    ]
