# Generated by Django 5.2 on 2025-05-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_cartitem_subtotal'),  # Adjust to your latest migration
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE ecommerce_cartitem DROP COLUMN sub_total;",
            reverse_sql="ALTER TABLE ecommerce_cartitem ADD COLUMN sub_total DECIMAL(12,2) DEFAULT 0.00;",
        ),
    ]