# Generated by Django 5.2 on 2025-05-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_remove_cartitem_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='unit_type',
            field=models.CharField(choices=[('pack', 'Pack')], default='pack', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_type',
            field=models.CharField(choices=[('pack', 'Pack')], default='pack', max_length=10),
        ),
    ]
