# Generated by Django 5.2 on 2025-05-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_remove_cartitem_sub_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'item', 'pricing_tier', 'unit_type', 'quantity')},
        ),
    ]
