# Generated by Django 5.2 on 2025-05-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_cartitem_unit_type_alter_orderitem_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
