# Generated by Django 5.2 on 2025-04-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_pricingtier_tier_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtier',
            name='no_end_range',
            field=models.BooleanField(default=False, help_text='Check if this tier has no end range (e.g., X+)'),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='range_end',
            field=models.PositiveIntegerField(blank=True, help_text="Leave blank if 'No End Range' is checked", null=True),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='tier_type',
            field=models.CharField(choices=[('pack', 'Pack'), ('pallet', 'Pallet')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pricingtierdata',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text="Price per pack if tier_type is 'pack', per pallet if 'pallet'", max_digits=10),
        ),
    ]
