# Generated by Django 5.2 on 2025-05-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_order_paid_receipt_order_refunded_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_note',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='delivery_notes/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_receipt',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='paid_receipts/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refunded_receipt',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='refunded_receipts/'),
        ),
    ]
