# Generated by Django 5.2 on 2025-05-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_cartitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='per_pack_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per pack (price per unit * units per pack)', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost before discounts (per pack price * quantity)', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='per_pack_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per pack (price per unit * units per pack)', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Total cost before discounts (per pack price * quantity)', max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pricingtierdata',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12),
        ),
    ]
