# Generated by Django 5.2 on 2025-05-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_order_delivery_note_alter_order_invoice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='ecommerce_o_order_i_0b16ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='ecommerce_o_pricing_704473_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='ecommerce_o_created_9448b8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pack_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pricing_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.pricingtier'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_type',
            field=models.CharField(choices=[('pack', 'Pack')], default='pack', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user_exclusive_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.userexclusiveprice'),
        ),
    ]
