# Generated by Django 5.2 on 2025-05-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_packs',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total number of packs across all cart items.'),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_units',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total number of units across all cart items.'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'item', 'pricing_tier', 'unit_type', 'quantity', 'updated_at')},
        ),
    ]
