# Generated by Django 5.2 on 2025-05-06 03:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_cart_total_packs_cart_total_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total weight of all items in the cart (in kilograms).', max_digits=12),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total weight of the item in the cart (in kilograms, based on item weight and quantity).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_type',
            field=models.CharField(choices=[('pack', 'Pack')], default='pack', max_length=10),
        ),
    ]
