# Generated by Django 5.2 on 2025-05-13 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'order item', 'verbose_name_plural': 'order items'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='ecommerce.item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pack_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pricing_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='ecommerce.pricingtier'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_type',
            field=models.CharField(choices=[('pack', 'Pack')], default='pack', editable=False, help_text="Unit type is fixed to 'pack'.", max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user_exclusive_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitem_items', to='ecommerce.userexclusiveprice'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'item', 'pricing_tier', 'pack_quantity', 'unit_type')},
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'item'], name='ecommerce_o_order_i_0b16ac_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['pricing_tier'], name='ecommerce_o_pricing_704473_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['created_at'], name='ecommerce_o_created_9448b8_idx'),
        ),
    ]
