# Generated by Django 5.2 on 2025-05-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_cartitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='per_unit_price',
            field=models.DecimalField(decimal_places=2, default=3, help_text='Price per unit from PricingTierData', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='per_unit_price',
            field=models.DecimalField(decimal_places=2, default=3, help_text='Price per unit from PricingTierData', max_digits=12),
            preserve_default=False,
        ),
    ]
