# Generated by Django 5.2 on 2025-05-17 07:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_alter_orderitem_options_alter_orderitem_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='refunded_payment_receipt',
            new_name='refund_payment_receipt',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='refunded_transaction_id',
            new_name='refund_transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refunded_receipt',
        ),
        migrations.AddField(
            model_name='order',
            name='refund_receipt',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='refund_receipts/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage (e.g., 10 for 10%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUND', 'Refund')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='VAT percentage (e.g., 20 for 20%).', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='ecommerce_o_user_id_20253d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='ecommerce_o_created_86a742_idx'),
        ),
    ]
