# Generated by Django 5.2 on 2025-05-06 03:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_cart_total_weight_cartitem_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='per_pack_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Price per pack, dynamically calculated as per_unit_price * units_per_pack.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='per_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Price per unit, dynamically retrieved from PricingTierData.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total cost before discounts, dynamically calculated based on per_pack_price and quantity.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total cost after user_exclusive_price discount, dynamically calculated.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_type',
            field=models.CharField(choices=[('pack', 'Pack'), ('pallet', 'Pallet')], default='pack', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total weight of the item in the cart (in kilograms), dynamically calculated based on item weight and quantity.', max_digits=12),
        ),
    ]
