# Generated by Django 5.2 on 2025-05-06 03:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_cartitem_per_pack_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total price of items in the cart, dynamically calculated as sum of item total_cost.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total after applying VAT and discount, dynamically calculated as subtotal + VAT - discount.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_packs',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total number of packs across all cart items, dynamically calculated.'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_units',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total number of units across all cart items, dynamically calculated.'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total weight of all items in the cart (in kilograms), dynamically calculated.', max_digits=12),
        ),
    ]
