# Generated by Django 5.2 on 2025-05-17 15:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
