# Generated by Django 5.2 on 2025-05-06 04:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_cart_subtotal_alter_cart_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total price of items in the cart (sum of item subtotals).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total after applying VAT and discount (subtotal + VAT - discount).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_packs',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total number of packs across all cart items.'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_units',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total number of units across all cart items.'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total weight of all items in the cart (in kilograms).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='per_pack_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per pack (price per unit * units per pack)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='per_unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit from PricingTierData', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total cost before user-exclusive discounts (per pack price * quantity, adjusted for unit type).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, help_text='Total cost after user_exclusive_price discount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_type',
            field=models.CharField(choices=[('pack', 'Pack')], default='pack', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total weight of the item in the cart (in kilograms, based on item weight and quantity).', max_digits=12),
        ),
    ]
