# Generated by Django 5.2 on 2025-05-06 04:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_cart_subtotal_alter_cart_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='per_pack_price',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Price per pack (price per unit * units per pack, automatically calculated)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='per_unit_price',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Price per unit from PricingTierData (automatically calculated)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total weight of the item in the cart (in kilograms, automatically calculated)', max_digits=12),
        ),
    ]
