# Generated by Django 5.2 on 2025-05-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_cartitem_per_pack_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_weight',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='per_pack_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='per_unit_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='weight',
        ),
    ]
