# Generated by Django 5.2 on 2025-05-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_remove_cart_subtotal_remove_cart_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='pack_quantity',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_type',
            field=models.CharField(choices=[('pack', 'Pack')], default='pack', editable=False, help_text="Unit type is fixed to 'pack'.", max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'item', 'pricing_tier', 'unit_type', 'pack_quantity', 'updated_at')},
        ),
    ]
