# Generated by Django 5.2 on 2025-05-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_rename_quantity_cartitem_pack_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_packs',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_units',
        ),
    ]
