# Generated by Django 5.2 on 2025-05-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_remove_cart_total_packs_remove_cart_total_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_packs',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total number of packs across all cart items.'),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_units',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total number of units across all cart items.'),
        ),
    ]
