# Generated by Django 5.2 on 2025-05-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_cart_total_packs_cart_total_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_packs',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_units',
        ),
    ]
