# Generated by Django 5.2 on 2025-05-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_remove_cart_total_packs_remove_cart_total_units'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'item', 'pricing_tier', 'pack_quantity', 'unit_type', 'updated_at')},
        ),
    ]
